### ISSUE TITLE
Initial review of the PCB

### ISSUE THREAD

**Issue by antoinealb** [cvra/front-panel-board#1]
Creating an issue for the review of the finished work. If you guys have time, would be great.

**Comment by msplr** [comment]
Quelques remarques:
* Si possible ajoute les 3dshapes dans le projet (pas forcément dans kicad-lib)
* Vu que les connecteurs CAN sont prévus d'être daisychained je mettrais une trace plus grande (~0.5mm)
* le placement des mounting holes a l'air un peu aléatoire. c'est bien pour l'intégration mécanique? Tu peux aussi documenter les côtes sur (Dwgs.User ou Cmts.User) et un screenshot dans le readme.

**Comment by antoinealb** [comment]
> Si possible ajoute les 3dshapes dans le projet (pas forcément dans kicad-lib)

Out of curiosity, c'est quoi l'idée derrière? Parce que dans le style guide ils mettent le footprint et la 3dshape ensemble.

> Vu que les connecteurs CAN sont prévus d'être daisychained je mettrais une trace plus grande (~0.5mm)

Ok, j'ai bump les traces de power

> le placement des mounting holes a l'air un peu aléatoire. c'est bien pour l'intégration mécanique? 

Romain a dit que je pouvais le mettre ou je voulais, donc j'ai mis là ou ca ne gêne pas le layout.

**Comment by msplr** [comment]
> Ok, j'ai bump les traces de power

Je mettrai aussi plus sur les lignes de CAN.

> c'est quoi l'idée derrière?

Pour que ça soit complet. Comme ça il faut pas les chercher sur internet pour une v2 ou un autre projet.

> Parce que dans le style guide ils mettent le footprint et la 3dshape ensemble.

Peu importe ou tu places les 3dshapes. J'aimerais que c'est packaged avec le projet.
